apiVersion: apps/v1
kind: Deployment
metadata:
  name: iot-simulator
  labels:
    app: iot-simulator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iot-simulator
  template:
    metadata:
      labels:
        app: iot-simulator
    spec:
      containers:
      - name: iot-simulator
        image: 211626350366.dkr.ecr.us-east-1.amazonaws.com/iot-simulator-repo:latest
        ports:
        - containerPort: 8080
        env:
        - name: KAFKA_BROKER
          value: "kafka-cluster-kafka-bootstrap.default.svc.cluster.local:9092"
        - name: KAFKA_TOPIC
          value: "iot-data"
        - name: KAFKA_SECURITY_PROTOCOL
          value: "SASL_PLAINTEXT"
        - name: KAFKA_SASL_MECHANISM
          value: "SCRAM-SHA-256"
        - name: KAFKA_SASL_JAAS_CONFIG
          valueFrom:
            secretKeyRef:
              name: kafka-user-passwords
              key: client-passwords