---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-cluster
spec:
  kafka:
    version: 3.3.1
    config:
      process.roles: broker,controller
      node.id: 1
      controller.quorum.voters: 1@kafka-cluster-kafka-0.default.svc.cluster.local
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      log.message.format.version: "3.3"
  kafkaNodePools:
    - name: kafka-pool
      replicas: 1
      roles:
        - broker
        - controller
      storage:
        type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {}