apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-streamer
  labels:
    app: spark-streamer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spark-streamer
  template:
    metadata:
      labels:
        app: spark-streamer
    spec:
      containers:
      - name: spark-streamer
        image: 211626350366.dkr.ecr.us-east-1.amazonaws.com/spark-streamer-repo:latest
        ports:
        - containerPort: 7077
        env:
        - name: KAFKA_BROKER
          value: "kafka-cluster-kafka-bootstrap.default.svc.cluster.local:9092"
        - name: KAFKA_TOPIC
          value: "iot-data"
        - name: KAFKA_SECURITY_PROTOCOL
          value: "SASL_PLAINTEXT"
        - name: KAFKA_SASL_MECHANISM
          value: "SCRAM-SHA-256"
        - name: KAFKA_SASL_JAAS_CONFIG
          valueFrom:
            secretKeyRef:
              name: kafka-user-passwords
              key: client-passwords